spring:
  application:
    name: netflix-api-gateway-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:8762/
server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka/'
zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    product-service:
      path: /products/**
      stripPrefix: false
